In [1]:
import numpy as np

In [ ]:
#array adalah sebuah matrix 1 dimensi dan dua dimenasi

In [ ]:
angka = [1,2,3]

In [ ]:
angkanp = np.array(angka)

In [ ]:
angkanp

In [ ]:
angka*3 #hasilnya bakalan nampilin 3 kali

In [ ]:
#kita mau yang didalam mdi kali 3, jadi vektor 1 dimensi
angkanp*3

In [12]:
versilist = [[1,2,3],[4,5,6],[7,8,8]] #cuma menampilkan list of list bukan sebuah matrix
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 8]]

In [13]:
versinumpy = np.array(versilist) #untuk menampilkan matrix menggunakan numpy
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [16]:
#mencreate dimana angka 1 dan angka terakhir
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#MEMBERIKAN jarak antara array
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.zeros(5) #megenerate array 0 sebnayak 5 angka

array([0., 0., 0., 0., 0.])

In [20]:
#matrix ddua dimensi
np.zeros((2,4)) #tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
#memvbangkitkan angka 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,8,10) #membuat array dari 0 sampai 8 dipecah , klo linspacce 8 dimasukkan/dipecah sebanyak 10 pecahan jarak angkaa satu dan selanjutnya sama

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

# Matriks identity

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Distribusi uniform

In [26]:
# bilangan distribusi uniform (0-1)
np.random.rand(7)

array([0.24991947, 0.68035884, 0.53061561, 0.63520496, 0.16564386,
       0.91401094, 0.42826563])

In [27]:
# bilangan distribusi unfotrm (0-1) pada matriks 2 dimensi
np.random.rand(5,4) #5 baris 4 kolom

array([[0.86479784, 0.71705451, 0.53957126, 0.43902011],
       [0.552034  , 0.76505133, 0.14115633, 0.00462639],
       [0.98529324, 0.39471027, 0.38816878, 0.40316273],
       [0.87632271, 0.96607969, 0.82841188, 0.23424081],
       [0.20905066, 0.11666109, 0.46625904, 0.6375017 ]])

In [29]:
#distribusi normal (gausssian) takhingga sampai tankl hingga
np.random.randn(10)

array([-1.32738687, -0.87221184, -0.60558686,  1.37836455,  0.6209224 ,
       -0.36178722, -1.75217043, -0.50538962, -1.16462173,  0.60836997])

In [30]:
# bilangan distribusi normal gaussioan taknhinnga dua dimensi
np.random.randn(4,4)

array([[ 0.2635791 ,  0.17327917,  0.40767983, -0.77818636],
       [-2.69508518, -0.53006823,  1.19365695,  0.0226909 ],
       [ 0.2419266 , -1.24077664,  1.35314038,  0.57438296],
       [-0.69486777,  0.34072527, -2.68757401,  1.57747746]])

In [3]:
#cara lebih gampangnya langsung importr saja
from numpy.random import randn, randint

In [33]:
randn(6,3) #tidak usah tulis depannya lagi

array([[ 0.50305332,  0.95826571, -0.47840914],
       [-0.6768637 ,  0.8507021 ,  0.24062694],
       [-0.2109353 , -2.29033094,  0.61356276],
       [ 0.89494514,  0.39044417, -0.58191921],
       [-0.19610795, -1.30506811, -0.00330317],
       [ 0.32590792, -0.48368009,  0.36435803]])

In [37]:
randint(0,20)

15

In [39]:
randint(0,10,2)

array([6, 0])

In [41]:
bilangan = randint(0,100,20)
bilangan

array([93, 52, 93, 65, 36, 21,  4, 70, 54, 77, 74, 50, 54, 76, 69, 17, 24,
       42, 69, 62])

In [42]:
#mengubah ukuran matriks haru pecahan dari 20 karena (0,100,20) karena jumlah angka 20 misal : 4x5
bilangan.reshape(2,1)

ValueError: cannot reshape array of size 20 into shape (2,1)

In [43]:
bilangan.reshape(4,5)

array([[93, 52, 93, 65, 36],
       [21,  4, 70, 54, 77],
       [74, 50, 54, 76, 69],
       [17, 24, 42, 69, 62]])

In [1]:
randint(0,3,5)

NameError: name 'randint' is not defined

In [2]:
randint(0,3,5)

NameError: name 'randint' is not defined

In [3]:
#cara lebih gampangnya langsung importr saja
from numpy.random import randn, randint

ModuleNotFoundError: No module named 'numpy'

In [5]:
randn(6,3)

array([[ 0.07941762,  0.81622465, -1.776645  ],
       [ 0.92114589, -0.35563542, -1.75253706],
       [ 0.13078537, -1.52569922,  0.22511947],
       [-0.67395232, -0.41974592, -1.77297788],
       [-0.77470158,  0.21172525,  0.61370385],
       [ 0.7735769 ,  0.01065477,  0.75469284]])

In [7]:
randint(0,10,20)

array([5, 3, 2, 5, 2, 5, 7, 8, 2, 1, 7, 4, 7, 0, 1, 4, 7, 2, 9, 2])

In [8]:
coba = randint(0,10,20).reshape(4,5) #menggunakan 2 fungsi secara besamaan
coba

array([[5, 9, 1, 1, 8],
       [7, 5, 0, 6, 6],
       [6, 4, 6, 7, 3],
       [6, 8, 1, 1, 6]])

In [4]:
np.linspace(0,8,9) #pemakaian tergantung mana

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [13]:
coba.max()#menggutnakan fungsi/method max

9

In [14]:
coba.min()

0

In [15]:
coba.argmax()

1

In [16]:
coba.argmin()

7

In [18]:
coba1 = randint(0,10,20)
coba1

array([7, 9, 1, 0, 1, 2, 8, 0, 3, 3, 1, 8, 1, 8, 7, 7, 1, 2, 5, 2])

In [20]:
coba2 = randint (0,10,20).reshape(4,5)
coba2

array([[6, 8, 2, 3, 8],
       [4, 9, 9, 1, 6],
       [5, 5, 7, 1, 5],
       [2, 7, 5, 4, 2]])

In [21]:
coba1.max() #mengurutkan dari depan nilai tertinggi yang pertaman yaitu 9

9

In [22]:
coba2.max()

9

In [23]:
coba1.min() #angka perama yaitu 0 min

0

In [24]:
coba2.min()

1

In [25]:
coba1.shape #menggunakai satu dimensi

(20,)

In [26]:
coba2.shape #menggunakan dua dimensi

(4, 5)

In [28]:
coba1.dtype #mencari tipe

dtype('int32')

# Indexing pada Numpy

In [52]:
indexing = np.arange(0,11)
indexing

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
indexing[6]

6

In [54]:
indexing[5:]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
indexing[1:4]

array([1, 2, 3])

In [56]:
indexing[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
coba3 = indexing.copy() #bagaimana agar tidak merubah nilai yg lain caranya pake copy contoh:


In [58]:
coba3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
coba3[:]=100
coba3


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
indexing #kalau di numpy kalau kita ubah nilai indexing maka coba3 akan berubah juga tidak seperti pada python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bil2d = np.array([[1,2,3],[4,5,6],[7,8,5]])
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 5]])

In [66]:
bil2d[2][0] #tidak direkomendiasikan

7

In [67]:
bil2d[1]

array([4, 5, 6])

In [68]:
bil2d[2,0] # yang direkomendasikan

7

In [69]:
bil2d[1,1:]

array([5, 6])

In [70]:
bil2d[1:2,1:]

array([[5, 6]])

# SLICING dengan bolean di Numpy

In [71]:
bil = np.arange(1,11)

In [72]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
angkaT = bil > 5

In [74]:
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
bil = bil[angkaT] #kita hanya menginginkan yang true saja
bil

array([ 6,  7,  8,  9, 10])

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# OPERASI di Numpy

In [83]:
coba = np.arange(0,11)
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
coba+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
coba_list = [1,2,3,4,5,5,67,7,8,99]

In [86]:
coba_list + coba_list

[1, 2, 3, 4, 5, 5, 67, 7, 8, 99, 1, 2, 3, 4, 5, 5, 67, 7, 8, 99]

In [87]:
coba*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [88]:
coba_list*2

[1, 2, 3, 4, 5, 5, 67, 7, 8, 99, 1, 2, 3, 4, 5, 5, 67, 7, 8, 99]

In [89]:
coba - coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
coba -100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [91]:
1/0 #klo perhitungan biasa hasilnya akan eror

ZeroDivisionError: division by zero

In [92]:
coba/coba #akan mengeluarkan nilai tpi ada warning

<ipython-input-92-4b181eb448c2>:1: RuntimeWarning: invalid value encountered in true_divide
  coba/coba


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
1/coba #coba punya angka 0, karena 1/0 tidak bisa tpi di numpy ttp bisa dihasilkan gtpi ada warning

<ipython-input-94-021fa7643746>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/coba


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [95]:
np.sqrt(coba) #akar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [96]:
np.exp(coba) #exponensial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [97]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# e =2.7182

In [98]:
np.max(coba)

10

In [99]:
coba.max()

10

In [100]:
coba.min()

0

In [101]:
np.min(coba)

0

In [102]:
np.sin(coba) #mencari nilai sin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [103]:
np.log(coba)

<ipython-input-103-953d5638885c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])