In [41]:
import numpy as np

In [3]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Append

In [4]:
np.append(my_arr, 10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
my_arr1 = np.array([[1, 2, 3],[4, 5, 6]])
my_arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.append(my_arr1, [
    [2, 2, 2],
    [3, 2, 2]
], axis=0)

#axis = 0 down, kalau axis = 1 vertikal

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2],
       [3, 2, 2]])

In [17]:
np.append(my_arr1,[
    [2, 34, 45],
    [3, 45, 34]
], axis=1)

array([[ 1,  2,  3,  2, 34, 45],
       [ 4,  5,  6,  3, 45, 34]])

# Concatenate

In [18]:
a = np.array([1, 2, 4, 6])
b = np.array([5, 6, 8, 8])

In [21]:
np.concatenate((a,b))

array([1, 2, 4, 6, 5, 6, 8, 8])

In [23]:
a = np.array([[1, 2, 3],
             [5, 7, 8]])
b = np.array([[7, 5, 8],
             [2, 4, 5]])
d = np.array([[3, 5, 3],
             [3, 5, 7]])

c = np.concatenate((b, a, d, b, a, d), axis =1 )
c

array([[7, 5, 8, 1, 2, 3, 3, 5, 3, 7, 5, 8, 1, 2, 3, 3, 5, 3],
       [2, 4, 5, 5, 7, 8, 3, 5, 7, 2, 4, 5, 5, 7, 8, 3, 5, 7]])

In [24]:
e = np.concatenate((b, a, d, b, a, d), axis =0 )
e

array([[7, 5, 8],
       [2, 4, 5],
       [1, 2, 3],
       [5, 7, 8],
       [3, 5, 3],
       [3, 5, 7],
       [7, 5, 8],
       [2, 4, 5],
       [1, 2, 3],
       [5, 7, 8],
       [3, 5, 3],
       [3, 5, 7]])

In [25]:
f = np.concatenate((b, a, d))
f

array([[7, 5, 8],
       [2, 4, 5],
       [1, 2, 3],
       [5, 7, 8],
       [3, 5, 3],
       [3, 5, 7]])

# Sorting

In [5]:
arr = np.array([
    [1, 5, 3, 4],
    [8, 65, 72, 8]
])

arr

array([[ 1,  5,  3,  4],
       [ 8, 65, 72,  8]])

In [6]:
np.sort(arr, axis = 0)

array([[ 1,  5,  3,  4],
       [ 8, 65, 72,  8]])

In [7]:
np.sort(arr, axis = 1)

array([[ 1,  3,  4,  5],
       [ 8,  8, 65, 72]])

# delete element of an array

In [10]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8,],
    [9, 10, 11, 12]
])

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
#delete baris 1
np.delete(arr, 1, axis =0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [13]:
np.delete(arr, [0,1], axis =0)

array([[ 9, 10, 11, 12]])

In [15]:
np.delete(arr, [0,2], axis = 0)

array([[5, 6, 7, 8]])

In [16]:
np.delete(arr, [0,1], axis = 1)

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

# Shape and size of an array

In [26]:
my_array = np.array([
    [[0, 1, 2, 3],
    [2, 3, 4, 5]],
    
    [[2, 3, 54, 6],
    [3, 4, 6, 8]],
    
    [[1, 3, 4, 67],
    [2, 4, 56, 7]]
])

my_array

array([[[ 0,  1,  2,  3],
        [ 2,  3,  4,  5]],

       [[ 2,  3, 54,  6],
        [ 3,  4,  6,  8]],

       [[ 1,  3,  4, 67],
        [ 2,  4, 56,  7]]])

In [30]:
my_array.ndim

#jumlah axes

3

In [28]:
my_array.size
#jumlah element

24

In [29]:
my_array.shape


(3, 2, 4)

# Reshaping an array


In [32]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
a.reshape(2,5, 1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [35]:
a. reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Exercise 3

In [43]:
c = np.arange(2,11)
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# matrix 3 x3
c.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [45]:
conc_array = np.array([
    [[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
])

conc_array

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [51]:
d = np.concatenate(conc_array, axis = 1)
d

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [53]:
np.newaxis(d, x=3)

TypeError: 'NoneType' object is not callable