In [6]:
import numpy as np #untuk menggunakan library Numpy / deklarasi library

In [1]:
#python list

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [2]:
print(a+b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
print(a*b) #bakalan error kare cuma list biasa saja

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
print(a*3)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


# Membuat Numpy Array

In [10]:
v = np.array([1, 2, 3, 4, 5])

print(v)
v

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [11]:
m = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])

m

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [15]:
m.dtype

v.dtype

dtype('int32')

In [19]:
type(m), type(v)

(numpy.ndarray, numpy.ndarray)

In [20]:
a = [1, 2, 3]

In [21]:
type(a)

list

In [24]:
v.shape()

TypeError: 'tuple' object is not callable

In [25]:
m,shape()

NameError: name 'shape' is not defined