## Adding, removing, and sorting elements

In [1]:
import numpy as np

### Append

In [2]:
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.append(my_arr, 10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

When axis is specified, values must have the correct shape.

In [4]:
my_arr1 = np.array([[1,2,3],
                    [2,4,6]])

In [8]:
np.append(my_arr1, [
    [2,2,2],
    [2,2,2]
], axis=0)

array([[1, 2, 3],
       [2, 4, 6],
       [2, 2, 2],
       [2, 2, 2]])

In [7]:
np.append(my_arr1, [
    [10,20],
    [10,20]
], axis=1)

array([[ 1,  2,  3, 10, 20],
       [ 2,  4,  6, 10, 20]])

### Concatenate

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [10]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a = np.array([[1, 2, 8],
              [5, 8, 10]])
b = np.array([[8, 2, 1],
              [3, 9, 1]])
d = np.array([[8, 2, 1],
              [3, 9, 1]])
c = np.concatenate((b, a, d, b, a, d), axis = 1)
print(c)

[[ 8  2  1  1  2  8  8  2  1  8  2  1  1  2  8  8  2  1]
 [ 3  9  1  5  8 10  3  9  1  3  9  1  5  8 10  3  9  1]]


In [ ]:
x = np.array([[1,2,3],
              [1,1,1]])
y = np.array([[3,3,1],
              [1,2,3]])
x = np.concatenate((x, y), axis = 1)
print(x)

In [16]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y)) #if axis = None, then arrays are flatten before use

array([[1, 2],
       [3, 4],
       [5, 6]])

### Sorting

In [17]:
# sorting np.sort()
arr = np.array([[1, 6, 3, 8],
               [5, 2, 7, 4]])
arr

array([[1, 6, 3, 8],
       [5, 2, 7, 4]])

In [18]:
np.sort(arr, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.sort(arr, axis=1)

array([[1, 3, 6, 8],
       [2, 4, 5, 7]])

### delete elements of an array

In [21]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### delete data in axis = 0

In [22]:
# delete 1 row
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [23]:
# delete rows from ... to ...
np.delete(arr, (0,1), axis=0)

array([[ 9, 10, 11, 12]])

In [24]:
# delete rows with specific index
np.delete(arr, [0,2], axis=0)

array([[5, 6, 7, 8]])

#### delete data in axis = 1

In [25]:
np.delete(arr, (0,1), axis=1)

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Shape and Size of an array

`ndarray.ndim` : the number of axes \
`ndarray.size` : the total number of element \
`ndarray.shape` : the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [26]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

In [27]:
my_array.ndim

3

In [28]:
my_array.size

24

In [29]:
my_array.shape

(3, 2, 4)

### Reshaping an array

When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [30]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [36]:
a.reshape(3, 2, 1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

## > Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](image/lat3.png)

### Converting a 1D array into 2D array (add a new axis to an array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

`np.newaxis` will increase the dimension of array by one whe it is used once. \
1D -> 2D, 2D -> 3D, and so on

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [46]:
a[2]

3

In [38]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [39]:
a2.shape

(1, 6)

In [40]:
# for a column vector, you can insert an axis along the second dimension
a3 = a[:, np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a3.shape

using `np.expand_dims`

In [41]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [42]:
# You can use np.expand_dims to add an axis at index position 1
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [43]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [44]:
# You can add an axis at index position 0 with
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [45]:
c

array([[1, 2, 3, 4, 5, 6]])

In [48]:
np.info(np.expand_dims)

 expand_dims(*args, **kwargs)

Expand the shape of an array.

Insert a new axis that will appear at the `axis` position in the expanded
array shape.

Parameters
----------
a : array_like
    Input array.
axis : int or tuple of ints
    Position in the expanded axes where the new axis (or axes) is placed.

    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as
        ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
        be treated as ``axis == 0``. This behavior is deprecated.

    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as
        described above are now forbidden and raise an `AxisError`.

Returns
-------
result : ndarray
    View of `a` with the number of dimensions increased.

See Also
--------
squeeze : The inverse operation, removing singleton dimensions
reshape : Insert, remove, and combine dimensions, and resize existing ones
doc.indexing, atleast_1d, atleast_2d, atleast_3d

Exa

## Indexing and slicing

In [49]:
data = np.array([1, 2, 3, 4, 5])

In [50]:
data[1]

2

In [52]:
data[:3]

array([1, 2, 3])

In [53]:
data[1:]

array([2, 3, 4, 5])

In [54]:
data[-2:]

array([4, 5])

In [60]:
data[1:4:3]

array([2])

In [63]:
data[::2]

array([1, 3, 5])

![](image/numpy.jpg)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [64]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [65]:
a[a < 7]

array([1, 2, 3, 4, 5, 6])

You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [66]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [ ]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

Or you can select elements that satisfy two conditions using the & and | operators:

In [70]:
c = a[(a > 2) | (a < 11)]
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [71]:
# pipe, or, vertical bar: |
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [72]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
a[1]

array([5, 6, 7, 8])

In [ ]:
a[1,1:3]

In [74]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9]],

       [[ 0,  2,  4],
        [ 6,  8, 10]]])

In [ ]:
z.shape

In [75]:
z[0] # access row 0

array([[0, 1, 3],
       [5, 7, 9]])

In [76]:
z[0,1] # access row 0, column 1

array([5, 7, 9])

In [79]:
z[0, 0:, 1:] #access row 0, column 1, depth 1-2

array([[1, 3],
       [7, 9]])

In [80]:
a = np.array([1,3,1,4,5,2,1])
a

array([1, 3, 1, 4, 5, 2, 1])

In [ ]:
a[1:4]

In [ ]:
a

# Creating an array from existing data

You can easily use create a new array from a section of an existing array.

In [84]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [83]:
a[5] = 100
print(a)
print(arr1)

[  1   2   3   4   5 100   7   8   9  10]
[  4   5 100   7   8]


In [85]:
import copy
b = copy.copy(a[3:8])
b

array([4, 5, 6, 7, 8])

In [86]:
a[6] = 100
print(a)
print(arr1)
print(b)

[  1   2   3   4   5   6 100   8   9  10]
[  4   5 100   7   8]
[4 5 6 7 8]


You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [87]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

a3 = np.array([[1, 1],
               [2, 2]])

a4 = np.array([[3, 3],
               [4, 4]])

In [90]:
np.hstack((a2, a1, a3, a4))

array([[3, 3, 1, 1, 1, 1, 3, 3],
       [4, 4, 2, 2, 2, 2, 4, 4]])

In [89]:
np.vstack((a1, a2, a3, a4))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

using `hstack`

In [ ]:
np.hstack((a1, a2))

You can split an array into several smaller arrays using `hsplit`. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [91]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [98]:
y = np.hsplit(x, 4)
y

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

If you want to split your array after the third and fourth column, you’d run:

In [ ]:
x

In [101]:
z = np.hsplit(x, (3, 7))

z

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

In [ ]:
m = np.hsplit(x, (1,3))

m

# Basic array operations

In [102]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [103]:
data

array([1, 2])

In [104]:
ones

array([1, 1])

In [105]:
data + ones

array([2, 3])

![](image/"np_data_plus_ones.png")

In [106]:
data - ones

array([0, 1])

In [107]:
data * data

array([1, 4])

In [108]:
data / data

array([1., 1.])

In [109]:
a = np.array([1, 2, 3, 4])

a.sum()

10

sum the rows/columns

In [112]:
b = np.array([[1, 1],
              [2, 2],
              [3,3]])
b.sum(axis=0)

array([6, 6])

In [113]:
b.sum(axis=1)

array([2, 4, 6])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [114]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![](image/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called <b> broadcasting </b>. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

# Working with Mathematical Formulas

The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

![](image/np_MSE_formula.png)

In [ ]:
mse = (1/n) * np.sum(np.square(y_pred - labels))

![](image/np_mse_viz1.png)

![](image/np_mse_viz2.png)

# How to save and load NumPy objects?

The ndarray objects can be saved to and loaded from the disk files with `loadtxt` and `savetxt` functions that handle normal text files, `load` and `save` functions that handle NumPy binary files with a .npy file extension, and a `savez` function that handles NumPy files with a .npz file extension.

If you want to store a single ndarray object, store it as a .npy file using np.save. If you want to store more than one ndarray object in a single file, save it as a .npz file using `np.savez`. You can also save several arrays into a single file in compressed npz format with `savez_compressed`.

In [115]:
a = np.array([1, 2, 3, 4, 5, 6])

In [117]:
np.save('./image/test_save', a)

In [118]:
# load file

b = np.load('test_save.npy')

In [119]:
b

array([1, 2, 3, 4, 5, 6])

You can save a NumPy array as a plain text file like a .csv or .txt file with `np.savetxt`.

In [ ]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.savetxt('myfile2.csv', csv_arr)

In [ ]:
np.loadtxt('myfile2.csv')

# ASSIGNMENT

1. create a null vector / 1D array of size 10 and update fifth value to 11.

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

4. Take a look at the following matrix. Show the data from [1, 1, 2] become [2, 1, 1]

5. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [1]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2], # this value
               [5, 2, 9],
               [1, 3, 3]]])


NameError: name 'np' is not defined

In [3]:
no5 = np.zeros((5,5))
no5

NameError: name 'np' is not defined

6. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [5]:
no6 = np.arrange(16).reshape(4,4)
no6

NameError: name 'np' is not defined